twikoojs/twikoo

- cloudbaserc.js
> fix(deploy): 修复Win10字符编码导致的部署失败

- docs/link.md
- docs/quick-start.md
> fix(0.2.1): 修复问题

- docs/.vuepress/theme/layouts/Layout.vue
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
- src/view/components/TkComment.vue
* 修复微信提醒
* 修复UA报错导致评论无法加载
* 修复config缓存导致配置不同步
> fix(0.2.2): 修复问题

- docs/.vuepress/theme/layouts/Layout.vue
- docs/faq.md
- docs/link.md
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
- src/view/components/TkAdmin.vue
- src/view/components/TkAvatar.vue
* 不输入密码直接点登录卡loading
* 完善文档
* 修复回复给博主，博主会收到2封邮件的问题
* 头像CDN替换回loli.net
> fix(0.2.3): 修复问题

- docs/.vuepress/theme/layouts/Layout.vue
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/view/App.vue
- src/view/components/TkAdminConfig.vue
- src/view/components/TkComment.vue
- src/view/components/TkComments.vue
* 新增 评论分页
* 修改 “查看更多...”的样式，避免深色模式下的“手电筒”
* 完善文档
> fix(0.2.6): 评论分页等

- docs/.vuepress/theme/layouts/Layout.vue
- docs/README.md
- docs/faq.md
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/js/utils/index.js
- src/view/components/TkComment.vue
* 修复 调用最新评论不能用自定义头像cdn #52
* 修复 通过QQ邮箱评论的，最新评论返回的avatar不是QQ头像 #53
* 完善文档
> fix(0.3.2): 修复 API 头像问题

- docs/.vuepress/theme/layouts/Layout.vue
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/view/components/TkAdminComment.vue
- src/view/components/TkComments.vue
- src/view/components/TkPagination.vue
- src/view/index.js
* 修复 访问 /path 时，无法获取到 /path/ 的评论
* 修复 分页造成的读取到的评论缺失
* 优化 重写分页组件，包体积减小100kb
> fix(0.3.3): 修复问题

- .npmignore
- docs/.vuepress/theme/layouts/Layout.vue
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/view/App.vue
- src/view/components/TkAdmin.vue
- src/view/components/TkAdminComment.vue
- src/view/components/TkAdminConfig.vue
- src/view/components/TkComment.vue
- src/view/components/TkMetaInput.vue
- src/view/components/TkPagination.vue
- src/view/components/TkSubmit.vue
- src/view/lib/owo.css
* 新增 评论管理可选分页大小
* 新增 自定义[昵称][邮箱][网址]必填/选填
* 修复 配置管理中的 secret key 改为密文
* 修复 评论管理中无法显示图片
* 修复 高分辨率的图片占地过大
* 修复 表情弹框被遮盖
* 修复 无法通过 URL#hash 跳转到指定评论
> fix(0.4.1): 修复问题

- docs/.vuepress/theme/layouts/Layout.vue
- docs/faq.md
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/js/utils/index.js
- src/view/components/TkAdminComment.vue
- src/view/components/TkComment.vue
- src/view/components/TkSubmit.vue
* 新增 QQ通知 #68
* 新增 可 hover 到相对时间上查看具体评论时间
* 改进 支持自定义 katex 参数
* 修复 微信、QQ、邮件推送的锚点不正确
* 修复 跳转到回复楼时，自动展开所在楼
> fix(0.4.3): 新增QQ通知，修复锚点问题

- docs/quick-start.md
add: [hexo-theme-ayer](https://github.com/Shen-Yu/hexo-theme-ayer)
> doc(quick): update doc

- src/view/components/TkSubmit.vue
> fix(0.4.5)

- .github/workflows/docs.yml
- docs/.vuepress/theme/layouts/Layout.vue
- docs/link.md
- docs/quick-start.md
* 增加相关文档
* 支持手动触发 Github Action 部署文档
> docs(link): 增加相关文档

- .github/workflows/build.yml
- .github/workflows/docs.yml
- package.json
Build failed after updating webpack from 4.44.1 to 5.11.1 (vuejs/vuepress#2753)
>  chore(ci): fix docs build action

- README.md
- docs/.vuepress/theme/layouts/Layout.vue
- docs/README.md
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
- src/js/utils/avatar.js
- src/view/components/TkMetaInput.vue
* 修复 style 注入问题
* 修复邮箱地址大小写问题 #119 
* 修复 AKISMET_KEY 不生效 #121
> fix(secure): 修复 style 注入问题，修复邮箱地址大小写问题，修复 AKISMET_KEY 不生效

- .gitignore
- docs/.vuepress/theme/layouts/Layout.vue
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
- src/js/utils/highlight.js
* 修复禁用高亮时，prism autoloader 仍然自动载入的问题 #125
* 升级 JS SDK 至 1.4.0
> fix(1.1.3-beta): 修复禁用高亮时，prism autoloader 仍然自动载入的问题

- docs/quick-start.md
- package.json
- src/function/twikoo/package.json
- src/lib/marked/Lexer.js
- src/lib/marked/README.md
- src/lib/marked/Renderer.js
- src/lib/marked/Tokenizer.js
- src/lib/marked/rules.js
* 修复 升级 marked 以修复 CVE-2021-21306 漏洞
> v1.2.2-beta

- docs/.vuepress/theme/layouts/Layout.vue
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
- src/js/utils/i18n/zh-CN.json
- src/js/utils/i18n/zh-HK.json
- src/js/utils/i18n/zh-TW.json
- src/view/App.vue
- src/view/components/TkAdminComment.vue
- src/view/components/TkAdminConfig.vue
- src/view/components/TkAdminImport.vue
- src/view/components/TkComments.vue
* 新增 支持配置一组违禁词，评论包含违禁词会被标记为垃圾评论
* 改进 垃圾评论不会再触发通知和提醒
* 改进 前端和云函数版本不一致时，管理面板会出现升级提醒
> v1.2.3-beta

- docs/.vuepress/theme/layouts/Layout.vue
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
- src/js/utils/i18n/zh-CN.json
- src/js/utils/i18n/zh-HK.json
- src/js/utils/i18n/zh-TW.json
- src/view/components/TkAdminComment.vue
- src/view/components/TkAdminConfig.vue
- src/view/components/TkComments.vue
- src/view/components/TkPagination.vue
* 新增 管理面板支持搜索评论
* 改进 增加“垃圾评论是否发送通知”的配置项，默认垃圾评论也发送通知
* 改进 没有评论时不再显示“0条评论”
* 改进 删除评论增加确认删除提示框
> v1.2.4-beta

- .github/workflows/publish.yml
- docs/.vuepress/theme/layouts/Layout.vue
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
* 新增 支持推送加（pushplus.hxtrip.com）推送评论提醒 #135
* 新增 支持配置一组违禁词，评论包含违禁词会被标记为垃圾评论
* 新增 管理员登录状态下，支持在评论列表置顶、隐藏评论 #118
* 新增 管理面板支持搜索评论
* 改进 删除评论增加确认删除提示框
* 改进 前端和云函数版本不一致时，管理面板会出现升级提醒
* 改进 增加“垃圾评论是否发送通知”的配置项，默认垃圾评论也发送通知
* 改进 没有评论时不再显示“0条评论”
* 改进 管理员发表的评论，将不再进行垃圾评论检测 #139
* 改进 管理员登录状态下，可以直接看到评论列表中所有的隐藏评论（显示为“审核中”）
* 改进 调整子评论样式，管理面板关闭按钮悬浮 #137 by @lete114
* 修复 升级 marked 以修复 CVE-2021-21306 漏洞
> feat(version): 发布 1.3.0 版本

- docs/.vuepress/theme/layouts/Layout.vue
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
> chore(func): lock cheerio version to rc.5

- docs/.vuepress/theme/layouts/Layout.vue
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
- src/vercel-min/package.json
- src/vercel/api/index.js
- src/vercel/package.json
- src/view/components/TkSubmit.vue
* 修复访客首次加载 Twikoo 时，会加载出已隐藏的评论，刷新后消失的问题
* 修复 Vercel 环境评论无法插入图片
> fix(vercel): 修复 Vercel 相关问题

- .github/workflows/publish.yml
- demo/demo.html
- docs/.vuepress/theme/layouts/Layout.vue
- docs/link.md
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
- src/js/utils/index.js
- src/vercel-min/package.json
- src/vercel/api/index.js
- src/vercel/package.json
- src/view/components/TkAdmin.vue
- src/view/components/TkAdminComment.vue
- src/view/components/TkAvatar.vue
- src/view/components/TkComment.vue
* 改进 评论人的网站和评论中的链接增加 rel="noopener noreferrer" 参数
* 修复 Vercel 环境评论管理，无法搜索评论
* 修复 部分主题下，评论管理，下拉框的选项，文字颜色为白色
> fix(vercel): fix search comment

- demo/demo.html
- src/js/utils/highlight.js
> [FIX] Set manual highlighting for Prism

- src/lib/owo.css
- src/view/App.vue
- src/view/components/TkAdmin.vue
- src/view/components/TkAdminComment.vue
- src/view/components/TkAvatar.vue
- src/view/components/TkComment.vue
- src/view/components/TkSubmit.vue
将所有8位数字的hex色值，替换为视觉上颜色一致的RGBA色值，解决Android微信里，8位hex色值不生效导致页面颜色异常的bug
> update hex to rgba

- demo/demo.html
- docs/quick-start.md
- src/js/main.all.js
- src/js/main.js
- src/js/utils/i18n/index.js
- src/js/utils/index.js
> [Feature] 添加自定义 `lang` 选项

- docs/.vuepress/theme/layouts/Layout.vue
- docs/faq.md
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
- src/js/utils/i18n/i18n.js
- src/vercel-min/package.json
- src/vercel/api/index.js
- src/vercel/package.json
- src/view/components/TkAdmin.vue
- src/view/components/TkAdminConfig.vue
- src/view/components/TkMetaInput.vue
- src/view/components/TkSubmit.vue
* 新增 允许限制一定时间内的评论数量，防御 IP 池刷评论 (#204)
* 新增 添加自定义语言选项 (#207 #208)
* 新增 init 时支持 placeholder (#210)
* 修复 Android微信里，8位hex色值不生效导致页面颜色异常 (#205)
> chore(version): update version 1.4.2

- docs/.vuepress/theme/layouts/Layout.vue
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
- src/vercel-min/package.json
- src/vercel/api/index.js
- src/vercel/package.json
* 修复 回复评论时，Vercel 邮件通知失败 #203 #215
* 修复 博主邮箱为空时，访客不填邮箱无法评论
* 修复 Valine 评论导入
> fix(func): fix vercel notice

- docs/.vuepress/theme/layouts/Layout.vue
- docs/quick-start.md
- package.json
- src/function/twikoo/index.js
- src/function/twikoo/package.json
- src/js/utils/i18n/i18n.js
- src/vercel-min/package.json
- src/vercel/api/index.js
- src/vercel/package.json
- src/view/components/TkAdminComment.vue
- src/view/components/TkComment.vue
* 新增 使用自行搭建企业微信通知api的及时提醒 #220
* 新增 收起评论回复 #216
* 改进 管理面板显示评论时间
* 改进 访客回复自己的评论不再收到邮件通知 #221
> feat(twikoo): serveral improvement

- src/view/components/TkComment.vue
给博主评论块添加识别用class，为博主访客评论样式分离提供可能。
> Update TkComment.vue ，给博主评论块添加识别用class

- docs/QQ_API.md
- docs/README.md
- src/function/twikoo/index.js
- src/js/entites/config.js
- src/js/utils/i18n/i18n.js
- src/vercel/api/index.js
- src/view/components/TkAdminConfig.vue
> 新增QQ私有化api部署

- docs/quick-start.md
* https://cdn.baomitu.com/twikoo
* https://github.com/imaegoo/twikoo/issues/320
> docs: add baomitu cdn mirror

- docs/quick-start.md
> Update quick-start.md - 修正Vercel部署项的一点点小错误

- src/js/utils/i18n/i18n.js
> Update i18n.js - 这个地方是不是写错了啊，看着不对劲🤣

- README.md
> Update README.md - 点击顶图打开twikoo官方网址

- README.en.md
- README.md
> 搞了个英文的Readme 望采纳 😆

- README.en.md
> Update README.en.md - 有个地方没打空格

- docs/.vuepress/theme/layouts/Layout.vue
- docs/quick-start.md
- package.json
- src/function/twikoo/package.json
- src/js/utils/api.js
- src/js/utils/highlight.js
- src/vercel-min/package.json
- src/vercel/package.json
- src/version.js
* 修复 无法获取最新评论
* 改进 允许自定义 Prism 加载地址，默认为从 jsDelivr CDN 加载
```js
twikoo.init({
// ......
// 默认为 'https://cdn.jsdelivr.net/npm/prismjs@1.23.0'
prismCdn: 'https://cdn.bootcdn.net/ajax/libs/prism/1.23.0',
})
```
> fix: cannot get recent comments

- docs/.vuepress/config.js
- docs/en/api.md
- docs/en/faq.md
> 英文文档更新 api文档和faq文档

- src/server/vercel-min/.github/dependabot.yml
Which allows the server version to be updated by the dependabot automatically
> feat: add dependabot.yml to vercel template

- src/client/view/components/TkAdminComment.vue
> add a dividing line in admin panel

- src/server/self-hosted/README.md
- src/server/self-hosted/server.js
自建后端增加`TWIKOO_LOCALHOST_ONLY`环境变量，以免同时在服务器上暴露http和其他软件反代后https的端口
> add TWIKOO_LOCALHOST_ONLY

- docs/link.md
该文章我最初发表于2022-03-16，目前总计2.2k字，帮助了很多博主成功部署了Twikoo，算是一个比较有用的免费部署教程。后续还在文章中更新了Vercel绑定自己的域名的教程，帮助解决DNS污染问题。
>  doc: add deployment tutorial link

- docs/quick-start.md
添加 [Hexo Theme Redefine](https://github.com/EvanNotFound/hexo-theme-redefine) 的 Twikoo 使用链接
> 添加 Redefine 主题 Twikoo 使用文档链接

- src/client/utils/i18n/i18n.js
> fix translation: Reviewing -> Pending

- src/client/utils/i18n/i18n.js
> i18n: improve zh-TW translation

- docs/quick-start.md
[https://stack.jimmycai.com/config/comments](https://stack.jimmycai.com/config/comments)
[https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config.yaml#L83](https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config.yaml#L83)
> 快速上手->前端部署 添加 hugo-theme-stack 主题

- src/client/utils/i18n/i18n.js
- src/server/self-hosted/index.js
- src/server/vercel/api/index.js
> 安全域名(CORS_ALLOW_ORIGIN)进行多域名适配，允许用户设置多个安全域名

- src/client/utils/i18n/i18n.js
- src/client/utils/i18n/index.js
Add Uzbek language translation
> Add Uzbek language translation

- src/client/view/components/TkAdminComment.vue
> add user-agent info in the comment admin panel

- src/client/utils/i18n/i18n.js
- src/client/view/components/TkAdminConfig.vue
- src/client/view/components/TkMetaInput.vue
- src/server/function/twikoo/utils/index.js
implement https://github.com/imaegoo/twikoo/issues/482
> add DISPLAYED_FIELDS config

- docs/en/quick-start.md
- docs/quick-start.md
- src/server/function/twikoo/index.js
- src/server/function/twikoo/utils/image.js
- src/server/function/twikoo/utils/index.js
- src/server/function/twikoo/utils/logger.js
- src/server/function/twikoo/utils/notify.js
- src/server/function/twikoo/utils/spam.js
- src/server/self-hosted/README.md
- src/server/self-hosted/index.js
- src/server/self-hosted/mongo.js
- src/server/self-hosted/server.js
- src/server/vercel/api/index.js
原有的console.log方式默认记录信息过多，自建服务时日志容易被撑爆
我仅测试了self-hosted部分，没有测试vercel等部分
> add logger for server

- docs/link.md
React/Next.js 前端应用中接入 Twikoo 前端文档链接申请
> React/Next.js 前端应用中接入 Twikoo 前端

- .gitignore
- demo/demo.html
- docs/.vitepress/theme/Twikoo.vue
- docs/backend.md
- docs/frontend.md
- package.json
- src/client/utils/i18n/i18n.js
- src/client/version.js
- src/client/view/components/TkAdminConfig.vue
- src/client/view/components/TkSubmit.vue
- src/server/function/twikoo/index.js
- src/server/function/twikoo/package.json
- src/server/function/twikoo/utils/index.js
- src/server/netlify/package.json
- src/server/self-hosted/index.js
- src/server/self-hosted/mongo.js
- src/server/self-hosted/package.json
- src/server/vercel/api/index.js
- src/server/vercel/package.json
[建议] 是否增加验证码？ #107 增加 https://developers.cloudflare.com/turnstile/ 验证码功能集成
建议添加根据屏蔽词直接删除垃圾信息功能 #631 增加屏蔽词功能
> feat: anti spam by captcha & blocked words

- src/client/utils/i18n/i18n.js
Japanese translations corrected to more common Japanese
> Update i18n.js (Japanese)

- docs/frontend.md
> add hexo solitude

- demo/demo.html
- docs/frontend.md
- src/client/utils/highlight.js
> chore: replace staticfile cdn domain

- demo/demo.html
- docs/.vitepress/theme/Twikoo.vue
- docs/frontend.md
- src/client/utils/highlight.js
这些CDN被指存在投毒行为
https://sansec.io/research/polyfill-supply-chain-attack
https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/
> doc: Remove bootcdn and staticfile CDN

- src/server/function/twikoo/utils/index.js
> fix: support harmony os user agent

- src/client/view/components/TkAdmin.vue
> 将密码输入框包裹在form中

- src/client/utils/i18n/i18n.js
- src/client/utils/i18n/index.js
I've completed the Korean translation for Twikoo.
I created a new branch named 'korean-translation' and modified the following files to add Korean language support:
- i18n.js
- index.js
I translated the original text so that even users who are not familiar with coding can understand what it is. (Because I'm the one.. it was a tough job.)
I hope I can be of help.
> Korean translation
