twikoojs/twikoo

- src/vercel/api/index.js
遇到的问题见 #226 
改动如下：
1. Vercel版本中发送邮件时调用了自身，设置300ms的timeout会导致axios超时而报错，所以移除了超时设置。
2. nodemailer与Vercel好像存在兼容问题，根据[这个贴子](https://stackoverflow.com/questions/65631481/nodemailer-in-vercel-not-sending-email-in-production)使用Promise套了一层。
3. 企业微信通知的环境变量未设置时没有判断，导致没有设置时也会向下执行，进而导致axios报错，所以加上了判断。
> 修复Vercel版本邮件不发送的问题

- src/vercel/api/index.js
今天发现又发送不了邮件通知了，摸索中发现了一个可能存在的问题：
由于我在Vercel给Twikoo配置了自定义域名，可能由于这个自定义域名的DNS在国内或者是其他原因，导致Vercel通过我的域名发送请求时经常发送不出去（具体原因仍然正在排查）
不过为了解决此问题，我想到Vercel有内置的`VERCEL_URL`环境变量，使用这个域名发送请求的话成功率必定要大的多，所以就把`POST_SUBMIT`的请求域名换成了从环境变量中获取，经测试没有任何问题。
> 使用VERCEL_URL域名来发送调用自身请求

- src/view/components/TkSubmit.vue
评论内容预览超出了预览框
回复评论的评论框没有问题，因为`.tk-comment`有`word-break: break-all;`
如下图所示
> fix: 🐛[bug] Comment length out of the preview box

- src/function/twikoo/index.js
- src/js/utils/i18n/i18n.js
- src/vercel/api/index.js
- src/view/components/TkAdminConfig.vue
>没写过相关语言，基本按 #220 照猫画虎
尝试为Twikoo引入钉钉机器人WebHook消息推送能力
安全认证设置为关键词，避免加签的麻烦
ToDo：
另：#176
> 我好像真的什么都不会，测试环境都没有
> 添加钉钉WebHook消息推送

- src/view/components/TkFooter.vue
When the `twikoo_visitors` property is not set, the `COUNTER_GET` request is not executed.
> flx: getCounter function

- src/function/twikoo/index.js
- src/vercel/api/index.js
如`223.16.3.51`，通过`btreeSearchSync`获取到的内容错误（以下为本地测试结果）：
改用为`binarySearchSync`后正常：
> fix: 部分ip获取到的数据为一堆占位符

- src/client/view/components/TkComment.vue
> add className for comment.ruser

- src/server/function/twikoo/utils/index.js
修复服务端获取QQ匿名头像的问题。
之前使用 #45 中的接口，但目前已经失效。
本 PR 修改了调用的接口。
当配置 `GRAVATAR_CDN` 为 `cravatar.cn` 时此问题不会显现。
因为 [Cravatar](https://cravatar.cn) 支持获取 QQ 头像。
> fix: get qq anonymous avatar

- src/client/utils/index.js
- src/client/view/components/TkFooter.vue
- src/client/view/components/TkSubmit.vue
在有**镜像站点**的情况下，允许管理员规范邮件通知使用的网址。
为前端 `twikoo.init` 方法新增 `href` 选项。
以及全局覆盖变量 `TWIKOO_MAGIC_HREF`。
用于指定相关接口的 `href` 参数。
尝试解决从镜像站点发送评论时，邮件通知里网址不统一的情况。
也就是模板中的 `${POST_URL}` 变量。
先自定义获取理想网址的方法。
```js
const getHref = () => {
const url = new URL(location);
url.protocol = 'https:';
url.hostname = 'example.com';
url.port = '';
return url.href;
};
```
然后在初始化评论区时调用并传入 `href` 选项。
```js
twikoo.init({
envId: 'https://comment.example.com',
el: '#tcomment',
href: getHref()
});
```
或者直接在网页中声明全局变量进行覆盖。
```js
Object.defineProperty(window, 'TWIKOO_MAGIC_HREF', {
configurable: true,
get: getHref
});
```
> feat: add `href` option

- src/client/utils/avatar.js
- src/client/utils/index.js
- src/client/view/components/TkAvatar.vue
- src/server/function/twikoo/index.js
- src/server/function/twikoo/utils/import.js
- src/server/function/twikoo/utils/index.js
- src/server/function/twikoo/utils/notify.js
- src/server/self-hosted/index.js
- src/server/self-hosted/mongo.js
- src/server/vercel/api/index.js
在进行电子邮箱地址相关的部分操作前，进行规范化处理。
Fix #585，已涵盖 #590。
1. 电子邮箱地址本就不区分大小写。
2. 参考 [Creating the Hash - Gravatar](https://cn.gravatar.com/site/implement/hash/) 和 [创建哈希值（Hash） - Cravatar](https://cravatar.com/developer/creating-the-hash)，计算哈希值前应规范化处理。
3. 不会因为大小写不同，导致博主标识不显示了。
4. 不用提醒访客，注意填写小写邮箱才能显示头像了。
5. 参考同类项目，保留了用户在大小写上体现个性，所以我放弃了强制小写邮箱的方案。
> fix: normalized mail

- src/client/utils/emotion.js
- src/client/utils/i18n/i18n.js
- src/client/utils/index.js
- src/client/view/components/TkSubmit.vue
> feat: support  split emotion cdn

- src/server/self-hosted/index.js
在私有部署，从 [Loki](https://github.com/techfort/LokiJS) 数据库导出数据时，包含了元信息。
```json
"meta": {
"revision": 0,
"created": 1672531200000,
"version": 0
},
"$loki": 1
```
在导入其他数据库时，这部分数据可能会产生冲突或错误。
比如在 [MongoDB](https://mongodb.com) 会报错 `key $loki must not start with '$'`。
我认为导出时，可以不包含这些非关键数据。
根据文档 [Class: Resultset - Method: data](https://techfort.github.io/LokiJS/Resultset.html#data) 用 `removeMeta` 选项可以实现。
> fix: export from loki should not include meta

- src/server/huggingface-space/Dockerfile
- src/server/huggingface-space/README.md
> Fix database reading issues and support new deployment methods

- .eslintignore
- .gitignore
- src/client/utils/i18n/i18n.js
- src/client/view/components/TkAdminConfig.vue
- src/client/view/components/TkComment.vue
- src/server/function/twikoo/utils/index.js
非常简单的点击图片放大功能
我不会vue所以实现的方式可能有一些小问题
> add simple lightbox

- src/server/deta/README.md
- src/server/deta/Spacefile
- src/server/deta/index.js
- src/server/deta/package.json
+ 添加云函数在 [Deta](https://deta.space) 的部署方式，函数代码使用 Express 框架实现。
> add: 添加云函数 Deta 部署功能

- docs/backend.md
- docs/mongodb-atlas.md
本 PR 对 MongoDB Atlas 账号的申请进行了扩充，增加了有关数据中心选择、IP 白名单、连接字符串的处理的最佳实践，并且将整个章节挪到一个单独的页面，方便多个部署方式引用。
> docs: improve MongoDB Atlas guide

- docs/faq.md
- package.json
- src/client/utils/i18n/i18n.js
- src/client/view/components/TkAdminComment.vue
- src/client/view/components/TkAvatar.vue
- src/client/view/components/TkSubmit.vue
- src/server/function/twikoo/utils/index.js
- src/server/function/twikoo/utils/lib.js
Closes #701
1. 头像采用 sha256 进行邮箱哈希，同时也兼容不支持 sha256 的 Cravatar
2. 默认使用 [WeAvatar](https://weavatar.com) 作为头像源（WeAvatar 支持 Cravatar 的所有功能）
3. 默认头像采用首字母（由 WeAvatar 提供）
4. 优化了头像相关函数的 if 结构
最终效果如图：
> feat: support sha256 avatar hash

- docs/frontend.md
See #715 
没有单独写一篇博客来介绍，感觉把内容放在原项目的 Issue 或 Discussion 中更稳定，有效避免将来博客跑路（是的我就是跑路大王）导致出现 Broken URL 的情况...
> docs(frontend): add vitepress integration link (#715)

- src/client/utils/i18n/i18n.js
- src/client/view/components/TkAdminConfig.vue
- src/server/function/twikoo/utils/index.js
- src/server/function/twikoo/utils/spam.js
> 支持腾讯内容安全的策略

- src/server/aws-lambda/terraform/main.tf
10 seconds are not enough to upload images in comments, so increase the timeout to 60 seconds.
现在default timeout是10秒，对于基础的API已经满足，但是如果在评论区上传图片会导致timeout，所以将timeout增加到60秒以支持上传图片。
> Increase AWS Lambda Timeout

- Dockerfile
使用`lts-alpine`能够减小构建出的image体积（本地测试从325MB缩小为了264MB，约60MB）。经过简单的测试，评论、邮件通知、实时通知、导入导出功能均正常。
同时修复了构建镜像时的警告`"ENV key=value" should be used instead of legacy "ENV key value" format`。
> chore(Dockerfile): Use Alpine image for smaller size

- src/client/utils/i18n/i18n.js
- src/client/view/components/TkAdminConfig.vue
- src/server/function/twikoo/utils/image.js
- src/server/function/twikoo/utils/index.js
[https://piclist.cn/](https://piclist.cn/)
> 添加PicList图床支持

- src/client/utils/i18n/i18n.js
- src/server/function/twikoo/utils/image.js
添加对 EasyImage2.0 简单图床的支持
简单图床 - 一款功能强大无数据库的图床 2.0版
Github：https://github.com/icret/EasyImages2.0
文档：https://icret.github.io/EasyImages2.0/#/
IMAGE_CDN_URL处填写网站的API调用地址，例如：https://img.example.com/api/index.php
IMAGE_CDN_TOKEN处填写网站生成的Token，例如：1c17b11693cb5ec63859b091c5b9c1b2
配置面板：
> 添加对EasyImage2.0图床的支持

- src/client/view/components/TkAvatar.vue
- src/server/function/twikoo/utils/index.js
Gravatar 今年初已支持首字母头像，因此需要同步调整参数（WeAvatar 已兼容更新后的参数，旧参数将于明年初下线）。
见：https://blog.gravatar.com/2025/02/19/initials-avatars-email-signatures/
> feat: 更新头像参数

- src/client/utils/i18n/i18n.js
- src/client/view/components/TkAvatar.vue
- src/server/function/twikoo/utils/index.js
在 PR #810 中引入了新的默认 Gravatar 头像 `initials&name=${this.nick.charAt(0)}`（对应版本号 1.6.43），但导致了前端的头像链接直接变成了字符串模板。
根据 Gravatar 官方的文档可以看到当设置 `d=initials` 的时候有两个选项，其中的 `name` 选项会由 Gravatar 自动摘取给定 name 中对应的 Initials，无需请求方处理。（同样的，weavatar 也兼容这个行为）
这个 PR 主要更改了 2 处内容：
1. 移除 `.charAt(0)` 方法，这个方法会在 `this.nick` 的值为 `undefined` 的时候抛出异常 `TypeError`。但在模板字符串中的时候值为 undefined 不会抛出异常。
2. 更新前端管理面板的 `_DEFAULT_GRAVATAR` 设置的提示文本，将 `identicon` 更改为 `initials`，并新增提示 `（留空）` 提示用户在这个值为空的时候对应的行为。
[直接链接到官方文档具体的位置](https://docs.gravatar.com/sdk/images/#:~:text=name%20%E2%80%93%20pass%20the%20name%20and%20have%20the%20initials%20be%20extracted)
下面是在 [https://twikoo.js.org/](https://twikoo.js.org/) 主页下方评论区的截图。
> fix(avatar): template literals occurred in url
